apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: janus-server
spec:
  serviceName: janus-discovery
  replicas: 1
  template:
    metadata:
      labels:
        app: janus-server
    spec:
      initContainers:
        - name: init-sysctl
          image: busybox:1.27.2
          command:
          - sysctl
          - -w
          - vm.max_map_count=262144
          securityContext:
            privileged: true
      containers:
        - name: elasticsearch
          image: quay.io/pires/docker-elasticsearch-kubernetes:6.1.2
          imagePullPolicy: IfNotPresent
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: DISCOVERY_SERVICE
            value: "janus-server"
          - name: CLUSTER_NAME
            value: janus
          - name: NUMBER_OF_MASTERS
            value: "1"
          - name: NODE_MASTER
            value: "true"
          - name: NODE_INGEST
            value: "false"
          - name: NODE_DATA
            value: "true"
          - name: HTTP_ENABLE
            value: "true"
          - name: ES_JAVA_OPTS
            value: -Xms512m -Xmx512m
          - name: PROCESSORS
            value: "4"
          ports:
          - containerPort: 9300
            name: transport
          - containerPort: 9200
            name: http
          livenessProbe:
            tcpSocket:
              port: transport
          volumeMounts:
          - name: janus-elasticsearch-storage
            mountPath: /data
        - name: cassandra
          image: cassandra:3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
            - containerPort: 9160
              name: thrift
          env:
            - name: CASSANDRA_SEEDS
              value: janus-server-0.janus-discovery.default.svc.cluster.local
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_CLUSTER_NAME
              value: "Janus"
            - name: CASSANDRA_DC
              value: "DC1"
            - name: CASSANDRA_RACK
              value: "Rack1"
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
            - name: CASSANDRA_START_RPC
              value: "true"
          volumeMounts:
            - name: janus-cassandra-storage
              mountPath: /var/lib/cassandra/data
        - name: janus-server
          image: eaybars/janus-server
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8182
            name: gremlin
      volumes:
          - hostPath:
              path: "/tmp/janus-cassandra"
              type: DirectoryOrCreate
            name: janus-cassandra-storage
          - hostPath:
              path: "/tmp/janus-elasticsearch"
              type: DirectoryOrCreate
            name: janus-elasticsearch-storage
