apiVersion: v1
kind: Service
metadata:
  labels:
    app: janus-server
  name: janus-server
spec:
  type: ClusterIP
  ports:
    - name: gremlin
      port: 8182
    - name: transport
      port: 9300
      protocol: TCP
    - name: http
      port: 9200
  selector:
    app: janus-server