apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
    role: all
spec:
  selector:
    component: elasticsearch
    role: all
  ports:
  - name: transport
    port: 9300
    protocol: TCP
  - name: http
    port: 9200
  type: ClusterIP
