apiVersion: batch/v1
kind: Job
metadata:
  name: orientdb-benchmark
  labels:
    app: orientdb-benchmark
spec:
  template:
    metadata:
      labels:
        app: orientdb-benchmark
    spec:
      restartPolicy: Never
      containers:
      - name: orientdb-benchmark
        image: eaybars/orientdb-benchmark
        imagePullPolicy: IfNotPresent
        args: ["insert", "-q"]
